// <auto-generated />
namespace MeetU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FullDesignForTag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FullDesignForTag));
        
        string IMigrationMetadata.Id
        {
            get { return "201601161050132_Full-Design-For-Tag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
