// <auto-generated />
namespace MeetU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenameForTagCreator : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameForTagCreator));
        
        string IMigrationMetadata.Id
        {
            get { return "201601161039553_Rename-For-Tag-Creator"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
