// <auto-generated />
namespace MeetU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class renametoimageFormat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renametoimageFormat));
        
        string IMigrationMetadata.Id
        {
            get { return "201602070541148_rename-to-imageFormat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
