// <auto-generated />
namespace MeetU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class setnicknameasnotnull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(setnicknameasnotnull));
        
        string IMigrationMetadata.Id
        {
            get { return "201603120407058_set-nick-name-as-not-null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
